In [ ]:
import numpy as np
import tools
import gym
env=gym.make('FrozenLake8x8-v1')

/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [ ]:
pip install tools

  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for tools: filename=tools-0.1.9-py3-none-any.whl size=46731 sha256=44276d2d5ef59f2f084ff563ab61743bb77dccd520e52f002c62a4dbe04484d7
  Stored in directory: /root/.cache/pip/wheels/c0/d0/70/a33bd4bed2af4f7038b038c16faab552cd0e9d9f4125223a71
  Created wheel for pytils: filename=pytils-0.4.1-py3-none-any.whl size=32536 sha256=f0180fb3e8976369d57fb6394f3786803a8f261f52b449fe41dfa276ec876547
  Stored in directory: /root/.cache/pip/wheels/5a/eb/7c/3b6f0c25815749883152b2caca34c35dbaab13ec2864270cbd
Successfully built tools pytils


In [ ]:
env.action_space

Discrete(4)

In [ ]:
env.action_space.n

4

In [ ]:
env.observation_space

Discrete(64)

In [ ]:
env.observation_space.n

64

In [ ]:
env.env.P[0][1]

[(0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 8, 0.0, False),
 (0.3333333333333333, 1, 0.0, False)]

In [ ]:
env.env.P[1][1]

[(0.3333333333333333, 0, 0.0, False),
 (0.3333333333333333, 9, 0.0, False),
 (0.3333333333333333, 2, 0.0, False)]

In [ ]:
def argmax(env,V,pi,action,s,gamma):
    e=np.zeros(env.action_space.n)
    for a in range(env.action_space.n):
        q=0
        P=np.array(env.env.P[s][a])
        (x,y)=np.shape(P)
        for i in range(x):
            s_=int(P[i][1])
            p=P[i][0]
            r=P[i][2]
            q+=p*(r+gamma*V[s_])
            e[a]=q
    m=np.argmax(e)
    action[s]=m
    pi[s][m]=1
    return pi

In [ ]:
def bellman_optimality_update(env,V,s,gamma):
    pi=np.zeros((env.observation_space.n,env.action_space.n))
    e=np.zeros(env.action_space.n)
    for a in range(env.action_space.n):
        q=0
        P=np.array(env.env.P[s][a])
        (x,y)=np.shape(P)
        for i in range(x):
            s_=int(P[i][1])
            p=P[i][0]
            r=P[i][2]
            q+=p*(r+gamma*V[s_])
            e[a]=q
    m=np.argmax(e)
    pi[s][m]=1
    value=0
    for a in range(env.action_space.n):
        u = 0
        P = np.array(env.env.P[s][a])
        (x,y) = np.shape(P)
        for i in range(x):

            s_= int(P[i][1])
            p = P[i][0]
            r = P[i][2]

            u += p*(r+gamma*V[s_])

        value += pi[s,a] * u

    V[s]=value
    return V[s]

In [ ]:
def value_iteration(env,gamma,theta):
    V=np.zeros(env.observation_space.n)
    while True:
        delta=0
        for s in range(env.observation_space.n):
            v=V[s]
            bellman_optimality_update(env,V,s,gamma)
            delta=max(delta,abs(v-V[s]))
        if delta<theta:
            break
    pi=np.zeros((env.observation_space.n,env.action_space.n))
    action = np.zeros((env.observation_space.n))
    for s in range(env.observation_space.n):
        pi = argmax(env, V, pi,action, s, gamma)         # extract optimal policy using action value

    return V, pi,action                                          # optimal value funtion, optimal policy


In [ ]:

gamma=0.99
theta=0.0001
V,pi, action=value_iteration(env,gamma,theta)

In [ ]:

V

array([0.41380427, 0.42646611, 0.44549747, 0.46775343, 0.49195119,
       0.51613512, 0.53484842, 0.54057219, 0.41087036, 0.42046608,
       0.43683661, 0.45781294, 0.4827469 , 0.51312584, 0.54539258,
       0.55701209, 0.3959509 , 0.39310776, 0.37485136, 0.        ,
       0.42127687, 0.49343747, 0.56087922, 0.58554475, 0.36850657,
       0.35230245, 0.30599599, 0.20012109, 0.30044703, 0.        ,
       0.56872722, 0.62798394, 0.33140018, 0.29058194, 0.19687072,
       0.        , 0.28905923, 0.36174158, 0.53457878, 0.68947802,
       0.30447888, 0.        , 0.        , 0.08615983, 0.21376735,
       0.27256811, 0.        , 0.77188416, 0.28695781, 0.        ,
       0.05729349, 0.0473396 , 0.        , 0.25045823, 0.        ,
       0.87769228, 0.27832491, 0.19924855, 0.12633303, 0.        ,
       0.23956772, 0.48639843, 0.73708127, 0.        ])

In [ ]:
pi

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],


In [ ]:
a=np.reshape(action,(8,8))
print(a)

[[3. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 2. 2. 1.]
 [3. 3. 0. 0. 2. 3. 2. 1.]
 [3. 3. 3. 1. 0. 0. 2. 2.]
 [0. 3. 0. 0. 2. 1. 3. 2.]
 [0. 0. 0. 1. 3. 0. 0. 2.]
 [0. 0. 1. 0. 0. 0. 0. 2.]
 [0. 1. 0. 0. 1. 2. 1. 0.]]


In [ ]:
action=tuple(action)

In [ ]:
action

(3.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 2.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 2.0,
 2.0,
 1.0,
 3.0,
 3.0,
 0.0,
 0.0,
 2.0,
 3.0,
 2.0,
 1.0,
 3.0,
 3.0,
 3.0,
 1.0,
 0.0,
 0.0,
 2.0,
 2.0,
 0.0,
 3.0,
 0.0,
 0.0,
 2.0,
 1.0,
 3.0,
 2.0,
 0.0,
 0.0,
 0.0,
 1.0,
 3.0,
 0.0,
 0.0,
 2.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 2.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 2.0,
 1.0,
 0.0)

In [ ]:
done = False
state = env.reset()
while not done:
    # Choose action based on the policy
    for i in action:
    # Take the action
        next_state, reward, done,t= env.step(i)

    # Print the observation (state, action, reward, next_state)
        print(f"State: {state}, Action: {i}, Reward: {reward}, Next State: {next_state}")

    # Update the current state for the next iteration
        state = next_state

# Close the environment
env.close()

State: 0, Action: 3.0, Reward: 0.0, Next State: 0
State: 0, Action: 2.0, Reward: 0.0, Next State: 0
State: 0, Action: 2.0, Reward: 0.0, Next State: 0
State: 0, Action: 2.0, Reward: 0.0, Next State: 0
State: 0, Action: 2.0, Reward: 0.0, Next State: 0
State: 0, Action: 2.0, Reward: 0.0, Next State: 8
State: 8, Action: 2.0, Reward: 0.0, Next State: 9
State: 9, Action: 2.0, Reward: 0.0, Next State: 17
State: 17, Action: 3.0, Reward: 0.0, Next State: 18
State: 18, Action: 3.0, Reward: 0.0, Next State: 19
State: 19, Action: 3.0, Reward: 0, Next State: 19
State: 19, Action: 3.0, Reward: 0, Next State: 19
State: 19, Action: 3.0, Reward: 0, Next State: 19
State: 19, Action: 2.0, Reward: 0, Next State: 19
State: 19, Action: 2.0, Reward: 0, Next State: 19
State: 19, Action: 1.0, Reward: 0, Next State: 19
State: 19, Action: 3.0, Reward: 0, Next State: 19
State: 19, Action: 3.0, Reward: 0, Next State: 19
State: 19, Action: 0.0, Reward: 0, Next State: 19
State: 19, Action: 0.0, Reward: 0, Next State